# -*- coding: utf-8 -*-
"""


@author: dougl
"""
import pickle
import nltk as distance
import Pycluster as PC
import numpy as np
import pandas as pd
import csv
import time
import matplotlib.pyplot as plt


t0 = time.process_time_ns()
DataSetTFG = [
'21HombreElectronicaVolleyballVideojuegosPeliculasThrillerIntrovertid@',
'25HombreElectronicaFutbolVideojuegosAmbasAccionExtrovertid@',
'20MujerTodoSurfGuitarraSeriesThrillerExtrovertid@',
'23HombreHip hopNingunoFiestaSeriesComediaExtrovertid@',
'21MujerTrapNingunoPasar tiempo en la naturaleza AmbasRomanticas Extrovertid@',
'20MujerRockTennisTocar guitarraPeliculasComediaIntrovertid@',
'19MujerTechnoGimnasiaFotografiaSeriesTerrorExtrovertid@',
'23HombreMetalCalisteniaBateria SeriesComedia Introvertid@',
'21HombrePopCriketEstudiarPeliculasDramaIntrovertid@',
'22MujerRockBaloncestoCervezaAmbasThrillerExtrovertid@',
'25HombreReggeaton Surf Videojuegos SeriesAccion Extrovertid@',
'22MujerChillVolleyball LeerAmbasAccion Extrovertid@',
'21MujerReggaetonVolleyballTocar el saxofon AmbasComedia Extrovertid@',
'19MujerReggaeton VolleyballPasar con amigos AmbasRom-comsExtrovertid@',
'23MujerPopGimnasioLas peliculasAmbasSuspenseExtrovertid@',
'21MujerReggaetonNatacionNetflix SeriesThrillerIntrovertid@',
'21MujerPopEjercicio en casaEscribirSeriesAccionExtrovertid@',
'22MujerPopSenderismoSalir a tomar algoSeriesSitcomsExtrovertid@',
'21MujerHeavy metalNatacionScrapbookingAmbasSitcomsIntrovertid@',
'21MujerRapGimnasioMuchos AmbasThrillerExtrovertid@',
'22MujerHardcoreYogaFotografia PeliculasThrillerIntrovertid@',
'22HombrePopDeportes de montanaLa montanaAmbasComedia Extrovertid@',
'22MujerIndieNingunoCineAmbasDramaExtrovertid@',
'20MujerPopGimnasioHobbieSeriesComediaExtrovertid@',
'20MujertechnoNingunoReposteriaAmbasAmorIntrovertid@',
'20MujerPopCorrer Tejer SeriesComedias Extrovertid@',
'21MujerNo tengoGimansioLeerAmbasTerrorIntrovertid@',
'22MujerPopRugbyCineAmbasThriller Extrovertid@',
'21MujerPopNatacion BaileAmbasRomanticas Introvertid@',
'21MujerPopNinguno LeerAmbasRomanticas Extrovertid@',
'22MujerReggaeton Ninguno Ver series SeriesDrama Introvertid@',
'22MujerNo tengo Ninguno BailarAmbasCiencia ficcion Extrovertid@',
'22MujerNo tengo Ninguno BailarAmbasCiencia ficcion Extrovertid@',
'20MujerPopGimnasioCocinarAmbasDrama Extrovertid@',
'25HombreIndieVolleyballGamingSeriesDibujos animadosIntrovertid@',
'17MujerIndieVolleyballVideojuegos AmbasHistoria Introvertid@',
'23MujerPopPole danceBailarAmbasComediaExtrovertid@',
'19MujerRockBaileLeer AmbasDramaIntrovertid@',
'20MujerIndieNingunoCantarAmbasTerrorIntrovertid@',
'21MujerPopNingunoCantarAmbasRomanceIntrovertid@',
'21MujerPopDanzaLeerAmbasPoliciacasExtrovertid@',
'23MujerRockNingunoIdiomas AmbasSuspensoExtrovertid@',
'23HombrePunkAtletismo Dibujo SeriesDramaIntrovertid@',
'20MujerRockTennisTocar guitarraPeliculasComediaIntrovertid@',
'21MujerPopPilatesLeerAmbasMisterioExtrovertid@',
'25MujerPopNingunoTeatroAmbasThrillerExtrovertid@',
'19MujerElectronica Tocho bandera Tocho Bandera AmbasAccion Introvertid@',
'18MujerPopSenderismoEstar con mi familia SeriesDrama Extrovertid@',
'23Hombreindie NingunoFotografiaAmbasAccion Introvertid@',
'21MujerIndieVolleyballLeerAmbasRom-comsIntrovertid@',
'21MujerIndieNatacionEstar al aire libreSeriesRomanticasIntrovertid@',
'20MujerR&BCrossFitHacer ejercicioPeliculasSuspensoIntrovertid@',
'19MujerPopNingunoLa musicaPeliculasRomanticasExtrovertid@',
'19MujerIndieTenniscocinar AmbasSuspensoExtrovertid@',
'19HombreSkaFutbolPcAmbasAccionIntrovertid@',
'18HombreRapNingunoLeerAmbasMisterioIntrovertid@',
'22MujerIndieNingunoDibujarAmbasSuspensoIntrovertid@',
'20HombreTodoVolleyball EscribirAmbasDramaExtrovertid@',
'20HombreTodoFutbolLeerAmbasAccion Extrovertid@',
'22MujerPop NingunoPasar con mi familiaAmbasRom-comsExtrovertid@',
'20HombreTechnoCrossfitVer seriesAmbasAccion Introvertid@',
'22HombreRapFutbol Fotografia PeliculasThrillerIntrovertid@',
'21MujerRockVolleyball La musica PeliculasComediaExtrovertid@',
'19MujerElectronica Tocho bandera Tocho Bandera AmbasAccion Introvertid@',
'25HombreRockFutbol Fotografia AmbasComedia Extrovertid@',
'20MujerRockTennisTocar guitarraPeliculasComediaIntrovertid@',
'21MujerReggaetonVolleyballTocar el saxofon AmbasSuspenso Extrovertid@',
'21MujerElectronica Futbol EscribirAmbasAnimeExtrovertid@',
'21MujerReggaetonVolleyballEscuchar musica AmbasAccion Extrovertid@',
'21MujerIndieBaseballTocar el saxofon AmbasSuspensoExtrovertid@',
'21HombreCorridosFutbolVideojuegosPeliculasTerrorIntrovertid@',
'22HombreHouseGolfVideojuegosSeriesSuspensoExtrovertid@',
'21MujerPopNinguno Dibujar AmbasAnimeIntrovertid@',
'24HombreReggaeton Futbol Jugar a la consolaAmbasAccion Extrovertid@',
'20MujerReggaeton NingunoEscuchar musica PeliculasComediaExtrovertid@',
'25HombreTech HouseNingunoe-sportsAmbasTerror PsicologicoIntrovertid@',
'24HombreRockFutbolHacer deporte AmbasSuspenso Introvertid@',
'21HombreReaggeton BaseballVer peliculas AmbasComediaExtrovertid@',
'25HombreMetalFutbol GymAmbasThrillerIntrovertid@',
'25HombrePunkFutbolEl GimnasioSeriessuspensoExtrovertid@',
'22HombreRapFutbolHacer ejercicio AmbasAccionExtrovertid@',
'21MujerPopHitDibujarAmbasRomanceExtrovertid@',
'25HombreBandaFutbol VideojuegosAmbasTodosIntrovertid@',
'19MujerFlamenco BaileHobbieSeriesCriminal Extrovertid@',
'23HombreTrap CiclismoJugar Xbox AmbasComedia Extrovertid@',
'24HombreSalsaFutbolVideojuegosSeriesMisterioIntrovertid@',
'25HombreUrbanoRunningDeportesPeliculasPolicialIntrovertid@',
'22HombreReggaeton Futbol Cocinar AmbasAccion Extrovertid@',
'22HombreRock FutbolGimnasioAmbasThrillerExtrovertid@',
'19MujerR&BNingunoLeerPeliculasAccion Introvertid@',
'19MujerPop NingunoBailarAmbasAmorExtrovertid@',
'20MujerPopNingunoEstudiar japones PeliculasTerror Introvertid@',
'20MujerReggaeton Ninguno CocinarAmbasRomanticas Extrovertid@',
'19MujerLatinoVolleyball Estar con amigosAmbasComedia Extrovertid@',
'24MujerReggaetonGimnasia RitmicaViajarPeliculasSuspenseIntrovertid@',
'19MujerPopTennisLeerAmbasAccion Introvertid@',
'20MujerR&BVolleyballDibujarAmbasComediasIntrovertid@',
'19MujerAlternativoEsgrimaMusicaSeriesCrimenIntrovertid@',
'20MujerRockNinguno Cantar AmbasRom-comsIntrovertid@',
'19MujerRockKarateDibujarAmbasRom-comsIntrovertid@',
'19MujerIndependiente AtletismoCocinarAmbasRom-comsExtrovertid@',
'20MujerElectro latinoVolleyballLeerPeliculasRom-comsExtrovertid@',
'19MujerPopNingunoCorrerSeriesComediaExtrovertid@',
'19MujerPop EsgrimaTocar violin AmbasComediaIntrovertid@',
'20MujerPopVolleyball LeerAmbasAccionIntrovertid@',
'21MujerPopNinguno Dibujar AmbasAnimeIntrovertid@',
'19MujerPopNingunoCorrerSeriesComediaExtrovertid@',
'19MujerPopNingunoVer seriesSeriesComediaExtrovertid@',
'25HombreBandaFutbol VideoJuegosAmbasTodosIntrovertid@',
'19MujerReggaetonNingunoleerSeriescrimenExtrovertid@',
'19MujerPopGymLeerSeriesDramaExtrovertid@',
'19MujerPopNo practico LeerPeliculasRomanticasExtrovertid@',
'20MujerPopNingunoLeerSeriesRomanticasExtrovertid@',
'24HombreRockFutbolHacer deporte AmbasSuspenso Introvertid@',
'25HombreEDMGymPatinar con long AmbasComedia Extrovertid@',
'19MujerReggaetonNingunoleerSeriescrimenExtrovertid@',
'19MujerRapNadaToco guitarraSeriesComedia Extrovertid@',
'22HombreReggaeton Futbol Cocinar AmbasAccion Extrovertid@',
'25HombreMoombathonGimnasioDjPeliculasAccion Extrovertid@',
'25HombreBandaFutbol VideoJuegosAmbasTodosIntrovertid@',
'22HombreRockFutbolGimnasioAmbasCiencia ficcion Extrovertid@',
'21MujerPopRunningDormirAmbasRomanticasIntrovertid@',
'20MujerReggaetonGimnasioBaileSeriesCiencia ficcion Extrovertid@',
'19HombrePopFutbolLeerSeriesFantasiaIntrovertid@',
'19MujerRockYogaCineAmbasComedia romanticaExtrovertid@',
'18MujerRapJudoLa montanaPeliculasComediaExtrovertid@',
'19MujerPopZumbaVer seriesSeriesDrama Extrovertid@',
'18MujerNingunoBaloncesto DeportePeliculasDramaIntrovertid@',
'19HombreTrapBaloncestoBaloncestoAmbasSuspenseExtrovertid@',
'19MujerPopDeporte en casaEscuchar musicaSeriesAmor adolescenteExtrovertid@',
'18MujerPopNinguno Ver seriesSeriesDramaIntrovertid@',
'18HombrePopCaminar DocumentalesSeriesIntriga Introvertid@',
'19MujerIndieGimnasioLeerSeriesRomanticasIntrovertid@',
'20MujerPopBaloncesto LeerSeriesSuspensoIntrovertid@',
'19HombreElectronicaCorrerCocinarPeliculasCiencia ficcionIntrovertid@',
'18MujerPopAtletismoMusicaAmbasThrillerIntrovertid@',
'20HombreHip hopNatacionSenderismoAmbasAccionExtrovertid@',
'21MujerIndie Andar MusicaSeriesAccionExtrovertid@',
'21MujerIndieGimnasioLeerSeriesDramaIntrovertid@',
'19MujerPopVolleyballCorrerAmbasAccionIntrovertid@',
'18MujerRockNingunoBailarAmbasMisterioIntrovertid@',
'21MujerNo tengo Correr Maquillaje AmbasComedia Introvertid@',
'19HombreTrapBaloncestoBaloncestoAmbasSuspensoExtrovertid@',
'18MujerPopAerobicEl movilSeriesPoliciacasExtrovertid@',
'25MujerRockCapoeiraViajarAmbasComedia Extrovertid@',
'18MujerPopCiclismoLeerSeriesMedicasIntrovertid@',
'19MujerIndieNingunoVer seriesSeriesComediaIntrovertid@',
'19MujerRapGimnasioCosturaSeriesMisterio Extrovertid@',
'20HombreRockGimnasioLeerPeliculasHumorExtrovertid@',
'20MujerPopVelaMusicaSeriesJuvenilIntrovertid@',
'22MujerSalsaFutbol CosturaPeliculasComediaExtrovertid@',
'18HombrePopFutbol Futbol AmbasCiencia ficcion Extrovertid@',
'20HombreTodoFutbol PlayStation SeriesDrama crimen Introvertid@',
'19HombreElectronica Futbol PlayStation AmbasCiencia Ficcion Introvertid@',
'24HombreBaladas FutbolNetflix SeriesComedias romanticas Extrovertid@',
'19HombreTrapFutbol Video juegos AmbasComedia Introvertid@',
'20HombreReggaetonFutbol DibujarAmbasMisterioExtrovertid@',
'19HombreElectronica Futbol PlayStation AmbasTerrorExtrovertid@',
'22MujerPopVolleyball LeerAmbasRom-comsExtrovertid@',
'20HombrePopFootballDeportesSeriesMisterioExtrovertid@',
'19HombreReggaeton Futbol PlayStation AmbasCiencia ficcion Introvertid@',
'20HombreMusica urbanaVolleyball Videojuegos AmbasMisterioIntrovertid@',
'19HombreReguetonTennisVideojuegosSeriesDramaIntrovertid@',
'25HombreRockFutbolVer series SeriesThrillerExtrovertid@',
'20HombreReggaetonVolleyballDibujarPeliculasTodasExtrovertid@',
'19HombreElectronicaFutbolProgramarSeriesSuspensoExtrovertid@',
'20MujerUrbano PescaCocinarPeliculasComediaExtrovertid@',
'22HombrePopFutbol Futbol AmbasMisterioIntrovertid@',
'18HombreRockFutbolNetflixPeliculasTerrorExtrovertid@',
'20HombreRapFutbolVideojuegosSeriesComediaIntrovertid@',
'18HombreElectronica Futbol PlayStation AmbasAccion Extrovertid@',
'20HombreIndieFutbolEscuchar musicaAmbasDramaExtrovertid@',
'18HombreElectronica Futbol PlayStation AmbasAccion Extrovertid@',
'19MujerPopYogaLeerSeriesDramaExtrovertid@',
'22HombrePopFutbol Futbol AmbasMisterioIntrovertid@',
'25HombreEDMGymPatinar con long AmbasComedia Extrovertid@',
'21MujerIndieGimnasioNetflixAmbasIntrigaIntrovertid@',
'19MujerPopAtletismoViajarPeliculasIntrigaIntrovertid@',
'25MujerRockCapoeiraViajarAmbasComedia Extrovertid@',
'22MujerRockNatacionCantarSeriesMisterioIntrovertid@',
'22HombreRap Futbol PlayStation AmbasComedia Extrovertid@',
'19MujerReggaetonNingunoLeerSeriesIntrigaExtrovertid@',
'20MujerPopEjercicio en casaLeerAmbasRomanticasExtrovertid@',
'21HombreSalsaVolleyball CorrerSeriesAccionIntrovertid@',
'19MujerIndieYogaLeerSeriesMisterioExtrovertid@',
'22MujerReggaetonVolleyball LeerAmbasDramaIntrovertid@',
'20MujerCorridosNinguno Tocho Bandera AmbasMisterioExtrovertid@',
'20MujerElectronicaFutbol ViajarSeriesComedias romanticas Introvertid@',
'21MujerPopNingunoDibujarAmbasSuspensoExtrovertid@',
'19HombreIndiePilatesEl movilSeriesCriminal Extrovertid@',
'20MujerTechnoFutbol Videojuegos PeliculasTodasExtrovertid@',
'20MujerLatinoCapoeiraPcAmbasAccion Extrovertid@',
'24MujerChillGimnasioCosturaPeliculasTerrorExtrovertid@',
'25MujerPop YogaLeerSeriesFantasiaExtrovertid@',
'24HombrePopCorrer ViajarAmbasComedia Extrovertid@',
'21MujerPopFutbol LeerAmbasComediaExtrovertid@',
'20HombrePopBaileLeerAmbasAccionExtrovertid@',
'22HombreEDMFutbolVer seriesPeliculasAccion Extrovertid@',
'25MujerRockNingunoHobbieAmbascrimenExtrovertid@',
'24MujerMusica urbanaNingunoleerAmbasSuspensoIntrovertid@',
'18MujerPopVolleyball CocinarPeliculasCiencia ficcionExtrovertid@',
'21MujerR&BNinguno PlayStation SeriesThrillerIntrovertid@',
'23MujerRockGimnasiaLeerAmbasComedia Introvertid@',
'22MujerTrapHitLeer PeliculasDramaExtrovertid@',
'25MujerReggeaton RunningLeerSeriesDramaIntrovertid@',
'20HombrePopNingunoTocar el saxofon AmbasSuspensoExtrovertid@',
'22MujerPopNingunoReposteriaPeliculasComediaExtrovertid@',
'19HombreTrapFutbolLeerSeriesThriller Extrovertid@',
'21MujerPopFutbolBateria AmbasComediaIntrovertid@',
'20HombreRapGimnasioLeerSeriesThrillerIntrovertid@',
'22HombreR&BFutbol CocinarSeriesRomanceIntrovertid@',
'25HombreReggaetonNingunoBaileAmbasAccion Extrovertid@',
'18MujerReggaeton DanzaCorrerSeriesRom-comsExtrovertid@',
'21MujerMetalGymFotografiaPeliculasMisterioExtrovertid@',
'23MujerElectronica Volleyball CineAmbasMisterio Introvertid@',
'22MujerRockBaseballJugar a la consolaPeliculasPoliciacasExtrovertid@',
'23MujerR&BNingunoDormirAmbasComedia Extrovertid@',
'19MujerPopNadaScrapbookingAmbasSuspenso Introvertid@',
'20MujerPopFutbol GimnasioAmbasAccion Introvertid@',
'19HombreRockFutbol Dibujar AmbasAmorExtrovertid@',
'19HombreRockNingunoMusicaAmbasSuspensoExtrovertid@',
'22MujerEDMFutbol Dibujar AmbasComedia Introvertid@',
'21MujerPopFutbol LeerAmbasAccion Introvertid@',
'20HombrePopFootballLeerAmbasComedia Extrovertid@',
'19HombreRockZumbaVer seriesSeriesTerrorExtrovertid@',
'19HombreReggaetonBaileBaloncestoSeriesCiencia ficcion Extrovertid@',
'19MujerPopFutbolToco guitarraSeriesComedia romanticaExtrovertid@',
'22HombreReggaeton Tocho bandera Escuchar musica AmbasMisterioExtrovertid@',
'25MujerNo tengoNatacionTocar violin SeriesDramaExtrovertid@',
'19HombrePopNatacionLa montanaSeriesIntrigaExtrovertid@',
'19MujerPopNingunoVer seriesAmbasAccion Introvertid@',
'20MujerPopNingunoFotografia AmbasAccionIntrovertid@',
'21MujerRock Futbol NetflixAmbasAccionExtrovertid@',
'18HombreElectronica TennisVer series SeriesDramaIntrovertid@',
'21HombrePopFutbolCocinar AmbasRomanticasIntrovertid@',
'22HombreElectronicaVolleyballJugar Xbox SeriesMisterioExtrovertid@',
'22HombrePopGimnasia RitmicaLa montanaSeriesTerrorIntrovertid@',
'18MujertechnoRugbyNetflixAmbasComediaIntrovertid@',
'21MujerTrapVolleyballFotografiaAmbasDramaIntrovertid@',
'19MujerElectronicaNatacionEscuchar musicaAmbasCrimenExtrovertid@',
'22MujerRapFutbolPlayStation SeriesRomanticasExtrovertid@',
'21HombreElectronica GolfCocinar AmbasRomanticasExtrovertid@',
'18HombreReggaeton NingunoSalir a tomar algoAmbasCiencia ficcion Extrovertid@',
'21MujerTech HouseCiclismoLeerAmbasTerror Introvertid@',
'22HombrePunkFutbol LeerAmbasSuspenseExtrovertid@',
'21HombreRapCalisteniaPlayStation PeliculasCiencia ficcion Introvertid@',
'18MujerPopNingunoVideo juegos AmbasDrama Introvertid@',
'20MujerPopAerobicSenderismoSeriesDramaExtrovertid@',
'20MujerUrbano GimansioGymAmbasSuspensoExtrovertid@',
'19MujerPopNatacionLeerSeriesComediaExtrovertid@',
'22MujerRockNingunoTocar guitarraAmbasAccionExtrovertid@',
'21HombreElectro latinoNinguno DeportesSeriesRom-comsIntrovertid@',
'20HombreBandaDeportes de montanae-sportsPeliculasDrama Introvertid@',
'22MujerReggaetonNinguno DibujarAmbasAccion Extrovertid@',
'20MujerSalsaFutbol Estudiar japones SeriesComediaExtrovertid@',
'19MujerRockNingunoFutbol SeriesMedicasIntrovertid@',
'18MujerIndieFutbol Ver series AmbasSuspensoIntrovertid@',
'22HombrePopPescaCantar AmbasCiencia ficcion Extrovertid@',
'22MujerIndieBaloncestoLeerPeliculasAccionExtrovertid@',
'20HombreNingunoSurf GuitarraPeliculasTerrorExtrovertid@',
'19MujerPopNingunoCantarSeriesTodosIntrovertid@',
'20MujerTrapNingunoCocinarAmbasAmorIntrovertid@',
'21MujerPopVolleyball DjAmbasAccionIntrovertid@',
'22MujerPopTennisTeatroSeriescrimenIntrovertid@',
'19HombreTodoFutbolMusicaPeliculasSuspensoExtrovertid@',
'21MujerPopFutbolPasar con amigos AmbasRomanticas Introvertid@',
'21HombreTrap Volleyball VideojuegosPeliculasThrillerExtrovertid@',
'19MujerTodoVolleyball LeerPeliculasComediaIntrovertid@',
'21HombreReggaeton GimnasioVideojuegos AmbasThrillerExtrovertid@',
'19MujerPopVolleyballLeerAmbasComedia Introvertid@',
'19MujerRockFutbol ProgramarPeliculasHumorIntrovertid@',
'21HombreTechnoSenderismoFotografia PeliculasComedia Extrovertid@',
'21HombreReggaeton FutbolBaloncestoSeriesThrillerExtrovertid@',
'18MujerRockBaloncestoDeportesAmbasComediaExtrovertid@',
'19MujerPop Tocho bandera VideojuegosSeriesAccion Introvertid@',
'20HombreRapTennisNetflix SeriesThrillerExtrovertid@',
'22MujerPopTennisCocinarSeriesPoliciacasIntrovertid@',
'25HombreIndieVelaVideojuegosSeriesComediaExtrovertid@',
'21HombreRapGimnasioDibujarAmbasRomanticasExtrovertid@',
'25HombreIndieGimnasioBailarSeriesTodosIntrovertid@',
'20HombreMetalGimnasioHobbieAmbasAccion Introvertid@',
'25MujerReggaetonVolleyballVideojuegosAmbasAccion Introvertid@',
'20MujerTodoFutbolBailarAmbasComedia Extrovertid@',
'19HombreAlternativoFutbol DibujarAmbasComediaExtrovertid@',
'19HombreRockNingunoVideoJuegosAmbasComediaExtrovertid@',
'20MujerIndependiente CapoeiraPlayStation AmbasComedia Introvertid@',
'20MujerBandaFutbol VideojuegosAmbasRom-comsExtrovertid@',
'19MujerPopBaloncesto Escuchar musica AmbasDramaIntrovertid@',
'25MujerRapFutbol LeerAmbasMisterioIntrovertid@',
'20HombrePopFutbolEscribirAmbasRom-comsIntrovertid@',
'25HombrePopCrossFitVideojuegosAmbasTodosExtrovertid@',
'24MujerElectronica Futbol LeerPeliculasThrillerIntrovertid@',
'19MujerReguetonVolleyballTocar guitarraAmbasComedia Introvertid@',
'23HombrePopRunningDeporteAmbasTerrorExtrovertid@',
'19HombreRockBaloncestoBailarPeliculasIntrigaExtrovertid@',
'20MujerRockVolleyballEscribirSeriesRomanticasIntrovertid@',
'21MujerReggaeton Deporte en casaFutbol AmbasSitcomsExtrovertid@',
'19MujerPopEsgrimaHacer ejercicio AmbasRom-comsIntrovertid@',
'19HombreRapNinguno Patinar con long AmbasComediaExtrovertid@',
'19HombreReggaetonGymVideojuegos AmbasComedia Extrovertid@',
'19HombreElectronica VolleyballMaquillaje SeriesRomanticas Extrovertid@',
'19MujerSkaNinguno Ver seriesSeriesRomanticas Extrovertid@',
'21MujerPopNingunoViajarSeriesSuspenseIntrovertid@',
'18HombrePunkFutbolPasar con mi familiaAmbasComedia Extrovertid@',
'18MujerHip hopNingunoHacer deporte SeriesAccion Extrovertid@',
'18MujerRockAndar DibujarAmbasDibujos animadosIntrovertid@',
'22MujerRockNingunoMuchos AmbasDramaExtrovertid@',
'19HombreReggaetonTennisGimnasioAmbasThrillerIntrovertid@',
'24MujerHip hopNingunoPlayStation SeriesSuspenso Introvertid@',
'21MujerHeavy metalAtletismoLeerAmbasDrama Extrovertid@',
'19MujerPopFutbolVideojuegosSeriesRom-comsIntrovertid@',
'19MujerReggaeton JudoMusicaAmbasTerror PsicologicoIntrovertid@',
'20Mujerindie VolleyballCineAmbasCiencia Ficcion Extrovertid@',
'21MujerIndieGimnasioEscuchar musicaSeriesAccion Introvertid@',
'18HombrePopNingunoTocho Bandera AmbasSuspenso Extrovertid@',
'25MujerNo tengo GimnasioLeerPeliculasRom-comsExtrovertid@',
'22MujerRapPole danceMusicaAmbasComediaExtrovertid@',
'25HombreIndieNingunoGamingSeriesComediaExtrovertid@',
'23HombreIndieFutbolPlayStation AmbasSitcomsExtrovertid@',
'19HombreRockNingunoFotografia AmbasHistoria Extrovertid@',
'22MujerUrbanoEsgrimaCantarAmbasComediaExtrovertid@',
'19MujerPop CiclismoTocar guitarraSeriesAnimeIntrovertid@',
'22MujerRockNingunoEstudiarAmbasRomanticas Introvertid@',
'21MujerPopSenderismoLa musica PeliculasAccionIntrovertid@',
'20MujerPopYogaDibujarAmbasComedia Introvertid@',
'17MujerElectronica NingunoTocar el saxofon AmbasThrillerExtrovertid@',
'21MujerPopBaseballPasar tiempo en la naturaleza SeriesSuspenseIntrovertid@',
'20MujerRap Futbol VideoJuegosAmbasDramaIntrovertid@',
'18HombreIndieAtletismoFutbol PeliculasThrillerExtrovertid@',
'20MujerBandaFutbolHacer deporte PeliculasComediaExtrovertid@',
'22MujerNo tengo Futbol PlayStation AmbasAccion Introvertid@',
'25MujerTodoCorrer Ver seriesAmbasMisterioIntrovertid@',
'19MujerReggaetonCrossfitEstar con mi familia AmbasThrillerExtrovertid@',
'25MujerFlamenco NingunoFiestaAmbasDrama Introvertid@',
'22HombreElectronica FutbolEstar al aire libreAmbasIntrigaIntrovertid@',
'19HombreHouseVolleyballNetflix AmbasComediasExtrovertid@',
'19MujerRockVolleyballVideojuegosAmbasComedias Introvertid@',
'23HombrePopNatacionBailarPeliculasRom-comsIntrovertid@',
'24MujerReaggeton CriketLeerSeriesDramaIntrovertid@',
'25MujerIndieGimnasioDocumentalesAmbasDramaExtrovertid@',
'18MujerReggaetonVolleyballHacer ejercicioPeliculasJuvenilExtrovertid@',
'21HombrePopAtletismoIdiomas AmbasAnimeIntrovertid@',
'23HombrePopCaminar CorrerAmbasThrillerExtrovertid@',
'21MujerIndieNinguno cocinar AmbasComediaExtrovertid@',
'19MujerPopNinguno CineAmbasMisterioExtrovertid@',
'20MujerPopSurfDibujo AmbasIntriga Extrovertid@',
'21MujerRockFutbolCantarPeliculasSuspensoIntrovertid@',
'19HombreRockBaloncesto CocinarPeliculasRomanceIntrovertid@',
'20HombreBaladas GimnasioPatinar con long AmbasCiencia ficcion Extrovertid@',
'20MujerElectronicaFutbol Tejer AmbasAccion Introvertid@',
'23HombreReggaetonCorrerBailarSeriesCiencia ficcion Introvertid@',
'20MujerMoombathonKarateLeerAmbasAnimeIntrovertid@',
'19MujerPopFutbol ViajarAmbasComediaExtrovertid@',
'21MujerNo tengo Natacion Tocar el saxofon SeriesPolicialExtrovertid@',
'20MujerIndieVolleyballBailePeliculasAccion Extrovertid@',
'25HombrePopGymCosturaSeriesMisterioExtrovertid@',
'19MujerIndieTennisLeerSeriessuspensoIntrovertid@',
'19HombreRockAtletismo Ver peliculas AmbasAccion Introvertid@',
'20HombreHardcoreFutbolEscribirSeriesComedia Extrovertid@',
'25MujerReggaetonNo practico El GimnasioSeriesDrama crimen Introvertid@',
'25MujerReggaeton Ninguno La musicaAmbasAmor adolescenteExtrovertid@',
'22HombrePopFutbol CervezaSeriesSuspensoExtrovertid@',
'19HombrePopFutbol Las peliculasSeriesTerrorIntrovertid@',
'19HombreIndie GimnasioEstar con amigosAmbasMisterioExtrovertid@',
'21HombrePopNatacion CocinarSeriesThrillerIntrovertid@',
'20MujerPopTennisTeatroAmbasMisterioIntrovertid@',
'25HombreNo tengo Futbol Ver seriesAmbasComediaExtrovertid@',
'25MujerRockFutbolLa musicaSeriesSuspensoIntrovertid@',
'22MujerRockNingunoCantarAmbasComedia Introvertid@',
'18MujerNo tengo FutbolLeerSeriesComedias Extrovertid@',
'22HombreRockVolleyballBailarSeriesTerror PsicologicoExtrovertid@',
'23HombrePopCiclismoSalir a tomar algoSeriesCiencia Ficcion Extrovertid@',
'19HombreIndieNingunoEscuchar musica AmbasSuspenso Extrovertid@',
'20MujerPopCorrerVideojuegosAmbasAccionExtrovertid@',
'19MujerReggaetonNingunoPlayStation AmbasThrillerExtrovertid@',
'20MujerReaggeton VolleyballCantar AmbasAccion Extrovertid@',
'23MujerPopBaloncestoPlayStation SeriesMisterioIntrovertid@',
'19MujerElectronica AtletismoCineAmbasComedia Extrovertid@',
'20MujerReggaetonBaloncestoPasar con mi familiaAmbasCiencia ficcion Extrovertid@',
'22MujerRapTennisMuchos SeriesAccion Introvertid@',
'21MujerPopGimnasioTocar violin AmbasComediaIntrovertid@',
'18HombreIndieNinguno FotografiaPeliculasRomanticasExtrovertid@',
'18MujerReggaeton Futbol Fotografia AmbasComediaExtrovertid@',
'20HombreBaladas VolleyballPatinar con long AmbasRomanticasExtrovertid@',
'19HombreTrap Baloncesto Videojuegos AmbasComediaExtrovertid@',
'19MujerPopVolleyball ViajarSeriesRom-comsIntrovertid@',
'20HombrePopGimnasioPlayStation AmbasThrillerIntrovertid@',
'21HombreRockFutbolFutbol AmbasThrillerExtrovertid@',
'20HombreIndependiente NatacionBailarAmbasRom-comsIntrovertid@',
'21MujerIndieGimnasioLeerAmbasAccion Extrovertid@',
'19MujerPopFutbolVideo juegos PeliculasDrama Introvertid@',
'19HombreUrbano GimnasioTejer SeriesJuvenilIntrovertid@',
'19MujerNingunoKarateEscuchar musica SeriesSuspensoIntrovertid@',
'20MujerIndieFutbol CantarSeriesComediaExtrovertid@',
'22HombreTech HouseGimnasioVer seriesSeriesPoliciacasIntrovertid@',
'21HombreReggaeton NatacionTocho Bandera AmbasThrillerIntrovertid@',
'19MujerPopNingunoViajarPeliculasThrillerExtrovertid@',
'21HombrePopVolleyballPlayStation AmbasRom-comsIntrovertid@',
'22HombreRockGymVideojuegosSeriesPolicialIntrovertid@',
'20MujerIndieFutbolVideojuegos PeliculasComediaExtrovertid@',
'20HombrePopGimnasioEscribirSeriesIntrigaExtrovertid@',
'19HombreSkaCriketDeporteSeriesTodosIntrovertid@',
'19HombreIndieNingunoLeerSeriesAccionIntrovertid@',
'22HombreNo tengoCrossfitEl GimnasioAmbasComediaExtrovertid@',
'20MujerPopFutbol Ver seriesAmbassuspensoIntrovertid@',
'18MujerPopEsgrimaDeportesPeliculasMisterioExtrovertid@',
'22HombrePopNingunoSenderismoAmbasHistoria Introvertid@',
'20MujerRockAerobicBailarAmbasComediaExtrovertid@',
'20MujerTechnoNinguno e-sportsPeliculasAccionExtrovertid@',
'25MujerRapGimansioVideoJuegosPeliculasTerrorIntrovertid@',
'21MujerRockVolleyballGimnasioPeliculasDrama crimen Introvertid@',
'21MujerReggaeton Futbol PlayStation SeriesAmor adolescenteExtrovertid@',
'23MujerRockVelaVer series AmbasRomanticas Extrovertid@',
'22MujerReggaetonSenderismoHobbieAmbasTerror Introvertid@',
'21MujerPopCapoeiraLeerPeliculasDramaIntrovertid@',
'25MujerMoombathonTennisEstudiar japones SeriesRomanceIntrovertid@',
'22HombrePopNingunoDibujarAmbasIntrigaExtrovertid@',
'18MujerElectronicaNingunoTocar guitarraSeriesThrillerExtrovertid@',
'19HombreElectronica TennisCocinar AmbasTerrorIntrovertid@',
'19HombreRock VolleyballCocinarPeliculasDramaIntrovertid@',
'25HombreAlternativoNingunoDjSeriesSuspensoIntrovertid@',
'22HombreRockGimnasiaProgramarSeriesMisterioIntrovertid@',
'25Mujerindie NingunoVideojuegosAmbasComedia Extrovertid@',
'21HombreRockYogaLeerSeriesRomanticas Introvertid@',
'21MujerElectronica NatacionBaloncestoPeliculasSuspensoIntrovertid@',
'19MujerPop No practico Netflix AmbasComediaExtrovertid@',
'24MujerSalsaCaminar Futbol SeriesCiencia ficcion Extrovertid@',
'19HombrePunkSurf Ver series AmbasDramaExtrovertid@',
'21MujerReggaetonCalisteniaPasar tiempo en la naturaleza PeliculasDramaExtrovertid@',
'22MujerPopNinguno LeerPeliculascrimenIntrovertid@',
'18MujertechnoNatacionTocar guitarraAmbasAccion Introvertid@',
'19HombreRap NingunoDibujo AmbasAccion Extrovertid@',
'22MujerRapJudoGymSeriesRom-comsIntrovertid@',
'21MujerElectronicaEsgrimaVideojuegosAmbasCiencia ficcion Extrovertid@',
'19HombreBandaBaloncesto GuitarraSeriesComedia Introvertid@',
'19HombreIndieVolleyball Pasar con amigos AmbasComedia Introvertid@',
'21MujerPopVolleyballBailarAmbasAnimeExtrovertid@',
'18HombreRockCiclismoEscuchar musicaAmbasAccionExtrovertid@',
'21MujerPopCrossFitLeerPeliculasDrama Extrovertid@',
'23HombreHardcoreTocho bandera Estar con amigosAmbasRomanticas Introvertid@',
'21MujerPopNinguno MusicaAmbasMisterioIntrovertid@',
'19MujerPopAtletismoTocar el saxofon AmbasTodosIntrovertid@',
'22MujerIndieFutbol DocumentalesAmbasCiencia ficcion Extrovertid@',
'20HombrePopPole danceVideojuegosAmbasIntrigaExtrovertid@',
'21MujerRockNingunoHacer ejercicioSeriesComediasExtrovertid@',
'20MujerIndieNingunoLas peliculasPeliculasThrillerExtrovertid@',
'18MujerElectronica SenderismoCorrerAmbasDrama Extrovertid@',
'25MujerPopFutbolJugar Xbox AmbasAccion Extrovertid@',
'25HombreIndieGolfPlayStation AmbasComediaIntrovertid@',
'20MujerPopFutbolNetflixAmbasAccion Introvertid@',
'19HombreReggaeton NingunoLeerAmbasAccionIntrovertid@',
'22MujerPopGimnasioLa montanaAmbasComediaIntrovertid@',
'21MujerBandaNinguno LeerAmbasAccionExtrovertid@',
'20HombrePopFutbolLeerSeriesDramaIntrovertid@',
'22HombreTrapTennisVideoJuegosAmbasDramaIntrovertid@',
'20MujerHousePescaMusicaSeriesCrimenIntrovertid@',
'25HombrePopFutbol VideojuegosSeriesSuspenseIntrovertid@',
'19MujerNo tengo FutbolPatinar con long AmbasDibujos animadosExtrovertid@',
'25MujerElectro latinoNinguno CosturaPeliculasMisterioIntrovertid@',
'19HombreReggaetonNingunoCervezaAmbasRomanticasExtrovertid@',
'22HombrePopTocho bandera Hacer deporte SeriesComedia Extrovertid@',
'21MujerBandaSurfFotografia SeriesDrama Introvertid@',
'21MujerTodoFutbol NetflixAmbasComediaIntrovertid@',
'18HombreIndieCorrer Netflix SeriesRomanticas Extrovertid@',
'19MujerReggaetonGimnasioFiestaAmbasAccion Introvertid@',
'19HombreElectronicaFutbol CantarAmbasDramaExtrovertid@',
'19MujerHeavy metalTennisFotografia PeliculasAccion Extrovertid@',
'21MujerReggaeton FutbolBailarAmbasCiencia ficcion Extrovertid@',
'19MujerPopFutbol Hacer deporte AmbasDramaExtrovertid@',
'19HombreTodoVolleyballBailePeliculasMedicasExtrovertid@',
'20MujerIndieDeporte en casaHacer ejercicio AmbasTodosExtrovertid@',
'18MujerElectronica Volleyball cocinar AmbasComediaIntrovertid@',
'19MujerPopNingunoDibujarAmbasTerrorExtrovertid@',
'20MujerReggaeton FutbolEstudiarAmbasRom-comsIntrovertid@',
'25HombreHip hopFutbolLeerAmbasSuspenso Introvertid@',
'25MujerRapFutbolEscribirAmbasSuspensoIntrovertid@',
'22HombreRapRunningMaquillaje SeriesRom-comsExtrovertid@',
'17MujerPopVolleyballCocinarAmbasDramaExtrovertid@',
'20HombreReggaetonFutbol LeerAmbasRomanticasExtrovertid@',
'19MujerMetalFutbol DeportesSeriesSuspenseIntrovertid@',
'22MujerRockNingunoLa montanaSeriesHumorExtrovertid@',
'20MujerRockAndar Estar al aire libreSeriesMisterioIntrovertid@',
'19HombreRockNatacionGamingAmbasThrillerIntrovertid@',
'18MujerPopNinguno CineSeriesRomanticasIntrovertid@',
'19MujerTodoGimnasioMusicaSeriesComediaExtrovertid@',
'25MujerUrbanoFutbol Futbol AmbasAmorExtrovertid@',
'18MujerTrapRugbyLa musica AmbasComediaExtrovertid@',
'21MujerReggaetonVolleyballVideojuegosPeliculasSitcomsExtrovertid@',
'24MujerPopNingunoIdiomas AmbasComedia Extrovertid@',
'20MujerReggaeton NingunoTocar el saxofon AmbasTerrorIntrovertid@',
'19MujerPunkAtletismoDibujarAmbasAnimeExtrovertid@',
'25HombrePop BaseballEscuchar musicaAmbasSitcomsExtrovertid@',
'21MujerReguetonFutbol EscribirAmbasAnimeIntrovertid@',
'23MujerRapDeportes de montanaTocar guitarraPeliculasIntriga Extrovertid@',
'24HombreIndie Atletismo DibujarAmbasComedia Introvertid@',
'19HombreElectronica BaloncestoVer peliculas AmbasComedia Extrovertid@',
'19HombreRapFutbolLeerSeriesAccion Extrovertid@',
'20MujerPopVolleyballVideojuegosAmbasSuspenseExtrovertid@',
'21HombreTodoGymCocinar AmbasAccion Introvertid@',
'19HombreHip hopVolleyballEstar con mi familia AmbasRom-comsIntrovertid@',
'19MujerFlamenco Futbol DibujarAmbasThrillerExtrovertid@']

#td*(0-1) saber el tiempo que toma ejecuatar cada parte del codigo
td0= time.process_time_ns()

#Get distance 
dist2 = [distance.edit_distance(DataSetTFG[i], DataSetTFG[j]) 
        for i in range(1, len(DataSetTFG))
        for j in range(0, i)]

#Tiempo Distancias
td1 = time.process_time_ns() - td0

#TiempoClusterK1
tc10 = time.process_time_ns()
#Cluster kmedoids K1 npass3
labels1, error1, nfound1 = PC.kmedoids(dist2, nclusters=1,npass=10)
#Guardamos el resultado en un dicionario cluster1
cluster1 = dict()
for roommate, label in zip(DataSetTFG, labels1):
    cluster1.setdefault(label, []).append(roommate)
for label, grp in cluster1.items():
    print(grp)
tc11 = time.process_time_ns() - tc10

#TiempoClusterK2
tc20 = time.process_time_ns()       
#Cluster kmedoids K2 npass3
labels2, error2, nfound2 = PC.kmedoids(dist2, nclusters=2,npass=10)
cluster2 = dict()
for roommate, label in zip(DataSetTFG, labels2):
    cluster2.setdefault(label, []).append(roommate)
for label, grp in cluster2.items():
    print(grp)
tc21 = time.process_time_ns() -tc20

#TiempoClusterK3
tc30 = time.process_time_ns()
#Cluster kmedoids K3 npass3
labels3, error3, nfound3 = PC.kmedoids(dist2, nclusters=3,npass=10)
cluster3 = dict()
for roommate, label in zip(DataSetTFG, labels3):
    cluster3.setdefault(label, []).append(roommate)
for label, grp in cluster3.items():
    print(grp)
tc31 = time.process_time_ns() -tc30

#TiempoClusterK4
tc40 = time.process_time_ns() 
#Cluster kmedoids K4 npass3
labels4, error4, nfound4 = PC.kmedoids(dist2, nclusters=4,npass=10)
cluster4 = dict()
w = csv.writer(open("Cluster410np.csv", "w"))
for roommate, label in zip(DataSetTFG, labels4):
    cluster4.setdefault(label, []).append(roommate)
    w.writerow([roommate, label])
for label, grp in cluster4.items():
    print(grp)
tc41 = time.process_time_ns() -tc40
#TiempoClusterK5   
tc50 = time.process_time_ns()
#Cluster kmedoids K5 npass3
labels5, error5, nfound5 = PC.kmedoids(dist2, nclusters=5,npass=10)
cluster5 = dict()
w1 = csv.writer(open("Cluster510np.csv", "w"))
for roommate, label in zip(DataSetTFG, labels5):
    cluster5.setdefault(label, []).append(roommate)
    w1.writerow([roommate, label])
for label, grp in cluster5.items():
    print(grp)

tc51 = time.process_time_ns() -tc50
#Calculo del tiempo desde procesado hasta imprimir resultados* sin guardar 
t1 = time.process_time_ns() -t0
#Time Distancias,

print("Tiempo procesado Texto Minutos:",(td1/60000000000))
print("Tiempo cluster1 Minutos", (tc11/60000000000))
print("Tiempo cluster2 Minutos", (tc21/60000000000))
print("Tiempo cluster3 Minutos", (tc31/60000000000))
print("Tiempo cluster4 Minutos", (tc41/60000000000))


print("Tiempo cluster5 Minutos", (tc51/60000000000))

print("Tiempo Programa Minutos", (t1/60000000000))
print("Cluster 4 Keys",cluster4.keys())
print("Cluster 5 Keys",cluster5.keys())

#ClusterResult K-4 & K-5 and save csv



#Guardamos cluster4y5, ya que son los que dan menor error. K4 seria la mejor opción
with open('cluster4TFGPF10np.pickle', 'wb') as f:
    pickle.dump(cluster4, f)
df= pd.DataFrame.from_dict(cluster4,orient='index').to_csv('cluster4TFGPF10np.csv')

with open('cluster5TFGPF.pickle', 'wb') as f:
    pickle.dump(cluster5, f)
df= pd.DataFrame.from_dict(cluster5,orient='index').to_csv('cluster5TFGPF10np.csv')
    


